version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:revierkompass123@db:5432/revierkompass?schema=public
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    networks:
      - revierkompass-network
    restart: unless-stopped

  db:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_DB=revierkompass
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=revierkompass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - revierkompass-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d revierkompass"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - revierkompass-network
    depends_on:
      - db

networks:
  revierkompass-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
