import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import { Building, ChevronDown, CheckCircle2 } from 'lucide-react';
import { animationVariants } from '../animations/variants';
const PraesidiumCard = ({ praesidium, onToggle, onExpand, onStationToggle, selectedStations, viewMode, expandedPraesidien }) => {
    const isSelected = selectedStations.includes(praesidium.id);
    const selectedReviere = praesidium.reviere.filter(r => selectedStations.includes(r.id));
    return (_jsxs(motion.div, { variants: animationVariants.card, initial: "rest", whileHover: "hover", whileTap: "tap", className: `p-6 rounded-xl border transition-all duration-200 ${isSelected
            ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20 shadow-md'
            : 'border-gray-200 dark:border-gray-600 hover:border-gray-300'}`, onClick: () => onToggle(praesidium.id), role: "button", tabIndex: 0, "aria-pressed": isSelected, children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Building, { className: "h-6 w-6 text-blue-600" }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white", children: praesidium.name }), _jsx("p", { className: "text-sm text-gray-600 dark:text-gray-400", children: praesidium.address }), praesidium.telefon && (_jsx("p", { className: "text-xs text-gray-500 dark:text-gray-500", children: praesidium.telefon }))] })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [praesidium.selectedCount > 0 && (_jsxs("div", { className: "px-2 py-1 bg-blue-100 dark:bg-blue-800 text-blue-800 dark:text-blue-200 text-xs rounded-full", children: [praesidium.selectedCount, "/", praesidium.reviere.length] })), _jsx(CheckCircle2, { className: `h-6 w-6 transition-colors ${isSelected ? 'text-blue-500' : 'text-gray-300 dark:text-gray-600'}` }), _jsx("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    onExpand();
                                }, className: "p-1 rounded-full hover:bg-blue-100 dark:hover:bg-blue-800 transition-colors", children: _jsx(ChevronDown, { className: `h-5 w-5 text-gray-400 transition-transform ${expandedPraesidien.has(praesidium.id) ? 'rotate-180' : ''}` }) })] })] }), viewMode === 'list' && (_jsxs("div", { className: "mb-4", children: [_jsxs("div", { className: "flex justify-between text-xs text-gray-500 mb-1", children: [_jsx("span", { children: "Auswahl-Fortschritt" }), _jsxs("span", { children: [selectedReviere.length, "/", praesidium.reviere.length] })] }), _jsx("div", { className: "w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2", children: _jsx("div", { className: "bg-blue-600 h-2 rounded-full transition-all duration-300", style: { width: `${(selectedReviere.length / praesidium.reviere.length) * 100}%` } }) })] })), viewMode === 'grid' && (_jsx(AnimatePresence, { children: expandedPraesidien.has(praesidium.id) && (_jsx(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: 'auto' }, exit: { opacity: 0, height: 0 }, className: "mt-4 space-y-2", children: praesidium.reviere.map(revier => (_jsxs("div", { className: `p-3 rounded-lg flex items-center justify-between cursor-pointer transition-colors ${selectedStations.includes(revier.id)
                            ? 'bg-blue-100 dark:bg-blue-800/30 text-blue-800 dark:text-blue-200'
                            : 'hover:bg-gray-50 dark:hover:bg-gray-700/50'}`, onClick: (e) => {
                            e.stopPropagation();
                            onStationToggle(revier.id);
                        }, children: [_jsxs("div", { className: "flex-1", children: [_jsx("span", { className: "text-sm font-medium", children: revier.name }), _jsx("p", { className: "text-xs text-gray-600 dark:text-gray-400 mt-1", children: revier.address }), revier.telefon && (_jsx("p", { className: "text-xs text-gray-500 dark:text-gray-500", children: revier.telefon }))] }), _jsx(CheckCircle2, { className: `h-5 w-5 transition-colors ${selectedStations.includes(revier.id)
                                    ? 'text-blue-500'
                                    : 'text-gray-300 dark:text-gray-600'}` })] }, revier.id))) })) }))] }));
};
export default PraesidiumCard;
