import { Station } from "@/types/station.types";

export const mockStations: Station[] = [
  // ========================================
  // STUTTGART PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-stuttgart',
    name: 'Polizeipräsidium Stuttgart',
    type: 'praesidium',
    city: 'Stuttgart',
    address: 'Hahnemannstraße 1, 70191 Stuttgart',
    coordinates: [48.81046, 9.18686],
    telefon: '0711 8990-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-stuttgart-1',
    name: 'Polizeirevier 1 Theodor-Heuss-Straße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Theodor-Heuss-Straße 11, 70174 Stuttgart',
    coordinates: [48.7769268, 9.1744498],
    telefon: '0711 8990-3100',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-2',
    name: 'Polizeirevier 2 Wolframstraße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Wolframstraße 36, 70191 Stuttgart',
    coordinates: [48.7922325, 9.1830113],
    telefon: '0711 8990-3200',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-3',
    name: 'Polizeirevier 3 Gutenbergstraße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Gutenbergstraße 109/111, 70197 Stuttgart',
    coordinates: [48.7700658, 9.1539327],
    telefon: '0711 8990-3300',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-4',
    name: 'Polizeirevier 4 Balinger Straße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Balinger Straße 31, 70567 Stuttgart',
    coordinates: [48.72991, 9.14272],
    telefon: '0711 8990-3400',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-5',
    name: 'Polizeirevier 5 Ostendstraße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Ostendstraße 88, 70188 Stuttgart',
    coordinates: [48.7837341, 9.2079634],
    telefon: '0711 8990-3500',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-6',
    name: 'Polizeirevier 6 Martin-Luther Straße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Martin-Luther-Straße 40/42, 70372 Stuttgart',
    coordinates: [48.80509, 9.22409],
    telefon: '0711 8990-3600',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-7',
    name: 'Polizeirevier 7 Ludwigsburger Straße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Ludwigsburger Straße 126, 70435 Stuttgart',
    coordinates: [48.8317597, 9.1746453],
    telefon: '0711 8990-3700',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  {
    id: 'rev-stuttgart-8',
    name: 'Polizeirevier 8 Kärntner Straße',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Kärntner Straße 18, 70469 Stuttgart',
    coordinates: [48.8131253, 9.16063],
    telefon: '0711 8990-3800',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-stuttgart'
  },
  // ========================================
  // MANNHEIM PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-mannheim',
    name: 'Polizeipräsidium Mannheim',
    type: 'praesidium',
    city: 'Mannheim',
    address: 'L6 1, 68161 Mannheim',
    coordinates: [49.483230, 8.467120],
    telefon: '0621 174-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-eberbach',
    name: 'Polizeirevier Eberbach',
    type: 'revier',
    city: 'Eberbach',
    address: 'Kellereistraße 33, 69412 Eberbach',
    coordinates: [49.46272, 8.98406],
    telefon: '06271 9210-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-heidelberg-mitte',
    name: 'Polizeirevier Heidelberg-Mitte',
    type: 'revier',
    city: 'Heidelberg',
    address: 'Rohrbacher Straße 11, 69115 Heidelberg',
    coordinates: [49.4065157, 8.6930257],
    telefon: '06221 1857-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-heidelberg-nord',
    name: 'Polizeirevier Heidelberg-Nord',
    type: 'revier',
    city: 'Heidelberg',
    address: 'Furtwänglerstraße 11, 69121 Heidelberg',
    coordinates: [49.42126, 8.68019],
    telefon: '06221 4569-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-heidelberg-sued',
    name: 'Polizeirevier Heidelberg-Süd',
    type: 'revier',
    city: 'Heidelberg',
    address: 'Bürgerstraße 47, 69124 Heidelberg',
    coordinates: [49.3789878, 8.6764057],
    telefon: '06221 3418-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-hockenheim',
    name: 'Polizeirevier Hockenheim',
    type: 'revier',
    city: 'Hockenheim',
    address: 'Werderstraße 8-10, 68766 Hockenheim',
    coordinates: [49.3181265, 8.5407761],
    telefon: '06205 2860-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-ladenburg',
    name: 'Polizeirevier Ladenburg',
    type: 'revier',
    city: 'Ladenburg',
    address: 'Bahnhofstraße 20-22, 68526 Ladenburg',
    coordinates: [49.471731, 8.603919],
    telefon: '06203 9305-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-innenstadt',
    name: 'Polizeirevier Mannheim-Innenstadt',
    type: 'revier',
    city: 'Mannheim',
    address: 'H4 1, 68159 Mannheim',
    coordinates: [49.4910013, 8.4656997],
    telefon: '0621 1258-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-kaefertal',
    name: 'Polizeirevier Mannheim-Käfertal',
    type: 'revier',
    city: 'Mannheim',
    address: 'Ladenburger Straße 3, 68309 Mannheim',
    coordinates: [49.5124314, 8.5182761],
    telefon: '0621 71849-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-neckarau',
    name: 'Polizeirevier Mannheim-Neckarau',
    type: 'revier',
    city: 'Mannheim',
    address: 'Reingoldplatz 4, 68199 Mannheim',
    coordinates: [49.45437, 8.48306],
    telefon: '0621 83397-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-neckarstadt',
    name: 'Polizeirevier Mannheim-Neckarstadt',
    type: 'revier',
    city: 'Mannheim',
    address: 'Waldhofstraße 32-34, 68169 Mannheim',
    coordinates: [49.4995783, 8.4718308],
    telefon: '0621 3301-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-oststadt',
    name: 'Polizeirevier Mannheim-Oststadt',
    type: 'revier',
    city: 'Mannheim',
    address: 'L6 1, 68161 Mannheim',
    coordinates: [49.48323, 8.46712],
    telefon: '0621 174-3310',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-mannheim-sandhofen',
    name: 'Polizeirevier Mannheim-Sandhofen',
    type: 'revier',
    city: 'Mannheim',
    address: 'Sonnenstraße 37c/d, 68307 Mannheim',
    coordinates: [49.5461914, 8.4481622],
    telefon: '0621 77769-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-neckargemuend',
    name: 'Polizeirevier Neckargemünd',
    type: 'revier',
    city: 'Neckargemünd',
    address: 'Bahnhofstraße 39, 69151 Neckargemünd',
    coordinates: [49.39309, 8.78452],
    telefon: '06223 9254-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-schwetzingen',
    name: 'Polizeirevier Schwetzingen',
    type: 'revier',
    city: 'Schwetzingen',
    address: 'Carl-Theodor-Straße 8, 68723 Schwetzingen',
    coordinates: [49.3845385, 8.5756366],
    telefon: '06202 288-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-sinsheim',
    name: 'Polizeirevier Sinsheim',
    type: 'revier',
    city: 'Sinsheim',
    address: 'Wilhelmstraße 7, 74889 Sinsheim',
    coordinates: [49.25386, 8.87891],
    telefon: '07261 690-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-weinheim',
    name: 'Polizeirevier Weinheim',
    type: 'revier',
    city: 'Weinheim',
    address: 'Am Hauptbahnhof 4, 69469 Weinheim',
    coordinates: [49.55348, 8.66625],
    telefon: '06201 1003-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  {
    id: 'rev-wiesloch',
    name: 'Polizeirevier Wiesloch',
    type: 'revier',
    city: 'Wiesloch',
    address: 'Schloßstraße 11-13, 69168 Wiesloch',
    coordinates: [49.29544, 8.6969613],
    telefon: '06222 5709-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-mannheim'
  },
  // ========================================
  // KARLSRUHE PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-karlsruhe',
    name: 'Polizeipräsidium Karlsruhe',
    type: 'praesidium',
    city: 'Karlsruhe',
    address: 'Durlacher Allee 31-33, 76131 Karlsruhe',
    coordinates: [49.0075455, 8.4258926],
    telefon: '0721 666-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-bad-schoenborn',
    name: 'Polizeirevier Bad Schönborn',
    type: 'revier',
    city: 'Bad Schönborn',
    address: 'Hauptstraße 11, 76669 Bad Schönborn',
    coordinates: [49.2062279, 8.6486305],
    telefon: '07253 8026-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-bretten',
    name: 'Polizeirevier Bretten',
    type: 'revier',
    city: 'Bretten',
    address: 'Weißhofer Straße 47, 75015 Bretten',
    coordinates: [49.0358073, 8.7117024],
    telefon: '07252 5046-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-bruchsal',
    name: 'Polizeirevier Bruchsal',
    type: 'revier',
    city: 'Bruchsal',
    address: 'Schönbornstraße 12-14, 76646 Bruchsal',
    coordinates: [49.1278202, 8.5994215],
    telefon: '07251 726-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-calw',
    name: 'Polizeirevier Calw',
    type: 'revier',
    city: 'Calw',
    address: 'Schloßberg 3, 75365 Calw',
    coordinates: [48.717534, 8.7350119],
    telefon: '07051 161-3511',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-ettlingen',
    name: 'Polizeirevier Ettlingen',
    type: 'revier',
    city: 'Ettlingen',
    address: 'Pforzheimer Straße 18, 76275 Ettlingen',
    coordinates: [48.9421391, 8.411131],
    telefon: '07243 3200-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-durlach',
    name: 'Polizeirevier Karlsruhe-Durlach',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Amthausstraße 11 - 13, 76227 Karlsruhe',
    coordinates: [48.9983685, 8.4715934],
    telefon: '0721 4907-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-marktplatz',
    name: 'Polizeirevier Karlsruhe-Marktplatz',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Karl-Friedrich-Straße 15, 76133 Karlsruhe',
    coordinates: [49.007832, 8.4040002],
    telefon: '0721 666-3311',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-oststadt',
    name: 'Polizeiposten Karlsruhe-Oststadt',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Durlacher Allee 31 - 33, 76131 Karlsruhe',
    coordinates: [49.007545, 8.425893],
    telefon: '0721 666-3211',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-suedweststadt',
    name: 'Polizeirevier Karlsruhe-Südweststadt',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Beiertheimer Allee 16, 76137 Karlsruhe',
    coordinates: [49.0020225, 8.3977478],
    telefon: '0721 666-3411',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-waldstadt',
    name: 'Polizeirevier Karlsruhe-Waldstadt',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Stettiner Straße 41, 76139 Karlsruhe',
    coordinates: [49.0323462, 8.4318192],
    telefon: '0721 96718-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-karlsruhe-west',
    name: 'Polizeirevier Karlsruhe-West',
    type: 'revier',
    city: 'Karlsruhe',
    address: 'Moltkestraße 68, 76133 Karlsruhe',
    coordinates: [49.0151313, 8.3757148],
    telefon: '0721 666-3611',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  {
    id: 'rev-philippsburg',
    name: 'Polizeirevier Philippsburg',
    type: 'revier',
    city: 'Philippsburg',
    address: 'Lessingstraße 10, 76661 Philippsburg',
    coordinates: [49.2381635, 8.4617278],
    telefon: '07256 9329-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-karlsruhe'
  },
  // ========================================
  // PFORZHEIM PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-pforzheim',
    name: 'Polizeipräsidium Pforzheim',
    type: 'praesidium',
    city: 'Pforzheim',
    address: 'Bahnhofstr. 13, 75172 Pforzheim',
    coordinates: [48.893076, 8.7007708],
    telefon: '+49 (0) 7231 / 186-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-muehlacker',
    name: 'Polizeirevier Mühlacker',
    type: 'revier',
    city: 'Mühlacker',
    address: 'Hindenburgstraße 100, 75417 Mühlacker',
    coordinates: [48.95231, 8.84832],
    telefon: '07041 9693-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-nagold',
    name: 'Polizeirevier Nagold',
    type: 'revier',
    city: 'Nagold',
    address: 'Oberamteistraße 6, 72202 Nagold',
    coordinates: [48.552021, 8.722196],
    telefon: '07452 9305-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-neuenbuerg',
    name: 'Polizeirevier Neuenbürg',
    type: 'revier',
    city: 'Neuenbürg',
    address: 'Bahnhofstraße 12, 75305 Neuenbürg',
    coordinates: [48.84722, 8.58889],
    telefon: '07082 7912-311',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-pforzheim-nord',
    name: 'Polizeirevier Pforzheim-Nord',
    type: 'revier',
    city: 'Pforzheim',
    address: 'Bahnhofstraße 13, 75172 Pforzheim',
    coordinates: [48.893107, 8.700933],
    telefon: '07231 186-3211',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-pforzheim-sued',
    name: 'Polizeirevier Pforzheim-Süd',
    type: 'revier',
    city: 'Pforzheim',
    address: 'Schwebelstraße 10, 75172 Pforzheim',
    coordinates: [48.891099, 8.684557],
    telefon: '07231 186-3311',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-freudenstadt',
    name: 'Polizeirevier Freudenstadt',
    type: 'revier',
    city: 'Freudenstadt',
    address: 'Marktplatz 47, 72250 Freudenstadt',
    coordinates: [48.464357, 8.409372],
    telefon: '07441 536-310',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'rev-horb',
    name: 'Polizeirevier Horb am Neckar',
    type: 'revier',
    city: 'Horb am Neckar',
    address: 'Neckarstraße 33, 72160 Horb am Neckar',
    coordinates: [48.444220, 8.690874],
    telefon: '07451 96-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-pforzheim'
  },
  {
    id: 'pp-freiburg',
    name: 'Polizeipräsidium Freiburg',
    type: 'praesidium',
    city: 'Freiburg',
    address: 'Bismarckallee 5, 79098 Freiburg',
    coordinates: [47.996, 7.8494],
    telefon: '0761 882-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-freiburg-nord',
    name: 'Polizeirevier Freiburg-Nord',
    type: 'revier',
    city: 'Freiburg',
    address: 'Bismarckallee 5, 79098 Freiburg',
    coordinates: [47.996, 7.8494],
    telefon: '0761 882-3100',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-freiburg'
  },
  {
    id: 'rev-freiburg-sued',
    name: 'Polizeirevier Freiburg-Süd',
    type: 'revier',
    city: 'Freiburg',
    address: 'Weismannstraße 8, 79106 Freiburg',
    coordinates: [47.9789, 7.8572],
    telefon: '0761 882-3200',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-freiburg'
  },
  {
    id: 'pp-konstanz',
    name: 'Polizeipräsidium Konstanz',
    type: 'praesidium',
    city: 'Konstanz',
    address: 'Benediktinerplatz 3, 78467 Konstanz',
    coordinates: [47.66898, 9.1797],
    telefon: '07531 995-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-friedrichshafen',
    name: 'Polizeirevier Friedrichshafen',
    type: 'revier',
    city: 'Friedrichshafen',
    address: 'Ehlersstraße 35, 88046 Friedrichshafen',
    coordinates: [47.659393, 9.486471],
    telefon: '07541 701-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-konstanz',
    name: 'Polizeirevier Konstanz',
    type: 'revier',
    city: 'Konstanz',
    address: 'Benediktinerplatz 3, 78467 Konstanz',
    coordinates: [47.66898, 9.1797],
    telefon: '07531 995-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-radolfzell',
    name: 'Polizeirevier Radolfzell am Bodensee',
    type: 'revier',
    city: 'Radolfzell am Bodensee',
    address: 'Güttinger Straße 1, 78315 Radolfzell am Bodensee',
    coordinates: [47.7396273, 8.9740013],
    telefon: '07732 95066-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-singen',
    name: 'Polizeirevier Singen',
    type: 'revier',
    city: 'Singen (Hohentwiel)',
    address: 'Julius-Bührer-Straße 6, 78224 Singen (Hohentwiel)',
    coordinates: [47.7589161, 8.8428238],
    telefon: '07731 888-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-stockach',
    name: 'Polizeirevier Stockach',
    type: 'revier',
    city: 'Stockach',
    address: 'Winterspürer Straße 27, 78333 Stockach',
    coordinates: [47.85142, 9.02147],
    telefon: '07771 9391-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-donaueschingen',
    name: 'Polizeirevier Donaueschingen',
    type: 'revier',
    city: 'Donaueschingen',
    address: 'Lehenstraße 2, 78166 Donaueschingen',
    coordinates: [47.95346, 8.49631],
    telefon: '0771 83783-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-oberndorf',
    name: 'Polizeirevier Oberndorf am Neckar',
    type: 'revier',
    city: 'Oberndorf am Neckar',
    address: 'Klosterstraße 3, 78727 Oberndorf am Neckar',
    coordinates: [48.292067, 8.574928],
    telefon: '07423 8101-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-rottweil',
    name: 'Polizeirevier Rottweil',
    type: 'revier',
    city: 'Rottweil',
    address: 'Kaiserstraße 10, 78628 Rottweil',
    coordinates: [48.16405, 8.62602],
    telefon: '0741 477-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-schramberg',
    name: 'Polizeirevier Schramberg',
    type: 'revier',
    city: 'Schramberg',
    address: 'Bahnhofstraße 5, 78713 Schramberg',
    coordinates: [48.229114, 8.384202],
    telefon: '07422 2701-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-schwenningen',
    name: 'Polizeirevier Schwenningen',
    type: 'revier',
    city: 'Villingen-Schwenningen',
    address: 'Oberdorfstraße 54, 78054 Villingen-Schwenningen',
    coordinates: [48.06277, 8.52662],
    telefon: '07720 8500-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-spaichingen',
    name: 'Polizeirevier Spaichingen',
    type: 'revier',
    city: 'Spaichingen',
    address: 'Hauptstraße 79, 78549 Spaichingen',
    coordinates: [48.07203, 8.74116],
    telefon: '07424 9318-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-tuttlingen',
    name: 'Polizeirevier Tuttlingen',
    type: 'revier',
    city: 'Tuttlingen',
    address: 'Stockacher Straße 158, 78532 Tuttlingen',
    coordinates: [47.97348, 8.82836],
    telefon: '07461 941-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  {
    id: 'rev-villingen',
    name: 'Polizeirevier Villingen',
    type: 'revier',
    city: 'Villingen-Schwenningen',
    address: 'Waldstraße 10/1, 78048 Villingen-Schwenningen',
    coordinates: [48.06477, 8.45252],
    telefon: '07721 601-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-konstanz'
  },
  // ========================================
  // OFFENBURG PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-offenburg',
    name: 'Polizeipräsidium Offenburg',
    type: 'praesidium',
    city: 'Offenburg',
    address: 'Prinz-Eugen-Straße 78, 77654 Offenburg',
    coordinates: [48.47991, 7.95363],
    telefon: '0781 21-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-achern-oberkirch',
    name: 'Polizeirevier Achern/Oberkirch',
    type: 'revier',
    city: 'Achern',
    address: 'Hauptstraße 105, 77855 Achern',
    coordinates: [48.628941, 8.079465],
    telefon: '07841 7066-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-baden-baden',
    name: 'Polizeirevier Baden-Baden',
    type: 'revier',
    city: 'Baden-Baden',
    address: 'Gutenbergstraße 15, 76532 Baden-Baden',
    coordinates: [48.77683, 8.21775],
    telefon: '07221 680-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-buehl',
    name: 'Polizeirevier Bühl',
    type: 'revier',
    city: 'Bühl',
    address: 'Hauptstraße 91, 77815 Bühl',
    coordinates: [48.6983699, 8.1376917],
    telefon: '07223 99097-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-gaggenau',
    name: 'Polizeirevier Gaggenau',
    type: 'revier',
    city: 'Gaggenau',
    address: 'Unimogstraße 7, 76571 Gaggenau',
    coordinates: [48.80173, 8.3125],
    telefon: '07225 9887-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-haslach',
    name: 'Polizeirevier Haslach i. K.',
    type: 'revier',
    city: 'Haslach im Kinzigtal',
    address: 'Schwarzwaldstraße 16, 77716 Haslach im Kinzigtal',
    coordinates: [48.2794373, 8.0882884],
    telefon: '07832 97592-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-kehl',
    name: 'Polizeirevier Kehl',
    type: 'revier',
    city: 'Kehl',
    address: 'Rathausplatz 4, 77694 Kehl',
    coordinates: [48.538248, 7.920639],
    telefon: '07851 893-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-lahr',
    name: 'Polizeirevier Lahr',
    type: 'revier',
    city: 'Lahr/Schwarzwald',
    address: 'Friedrichstraße 17, 77933 Lahr/Schwarzwald',
    coordinates: [48.3416497, 7.8747662],
    telefon: '07821 277-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-offenburg',
    name: 'Polizeirevier Offenburg',
    type: 'revier',
    city: 'Offenburg',
    address: 'Hauptstraße 96, 77652 Offenburg',
    coordinates: [48.46886, 7.94252],
    telefon: '0781 21-2200',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  {
    id: 'rev-rastatt',
    name: 'Polizeirevier Rastatt',
    type: 'revier',
    city: 'Rastatt',
    address: 'Engelstraße 31, 76437 Rastatt',
    coordinates: [48.86078, 8.20282],
    telefon: '07222 761-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-offenburg'
  },
  // ========================================
  // RAVENSBURG PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-ravensburg',
    name: 'Polizeipräsidium Ravensburg',
    type: 'praesidium',
    city: 'Ravensburg',
    address: 'Gartenstraße 97, 88212 Ravensburg',
    coordinates: [47.7928276, 9.622915],
    telefon: '+49 (0) 751 / 803-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-bad-saulgau',
    name: 'Polizeirevier Bad Saulgau',
    type: 'revier',
    city: 'Bad Saulgau',
    address: 'Hauptstraße 119, 88348 Bad Saulgau',
    coordinates: [48.01332, 9.5034],
    telefon: '07581 482-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-leutkirch',
    name: 'Polizeirevier Leutkirch',
    type: 'revier',
    city: 'Leutkirch im Allgäu',
    address: 'Karlstraße 8, 88299 Leutkirch im Allgäu',
    coordinates: [47.826385, 10.019782],
    telefon: '07561 8488-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-ravensburg',
    name: 'Polizeirevier Ravensburg',
    type: 'revier',
    city: 'Ravensburg',
    address: 'Seestraße 11, 88214 Ravensburg',
    coordinates: [47.778238, 9.612080],
    telefon: '0751 803-3333',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-sigmaringen',
    name: 'Polizeirevier Sigmaringen',
    type: 'revier',
    city: 'Sigmaringen',
    address: 'Karlstraße 15, 72488 Sigmaringen',
    coordinates: [48.08527, 9.22126],
    telefon: '07571 104-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-ueberlingen',
    name: 'Polizeirevier Überlingen',
    type: 'revier',
    city: 'Überlingen',
    address: 'Mühlenstraße 16, 88662 Überlingen',
    coordinates: [47.76441, 9.16577],
    telefon: '07551 804-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-wangen',
    name: 'Polizeirevier Wangen im Allgäu',
    type: 'revier',
    city: 'Wangen im Allgäu',
    address: 'Lindauer Straße 38, 88239 Wangen im Allgäu',
    coordinates: [47.684606, 9.828214],
    telefon: '07522 984-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'rev-weingarten',
    name: 'Polizeirevier Weingarten',
    type: 'revier',
    city: 'Weingarten',
    address: 'Promenade 13/1, 88250 Weingarten',
    coordinates: [47.811509, 9.637479],
    telefon: '0751 803-6666',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ravensburg'
  },
  {
    id: 'pp-einsatz',
    name: 'Polizeipräsidium Einsatz',
    type: 'praesidium',
    city: 'Göppingen',
    address: 'Heininger Straße 100, 73037 Göppingen',
    coordinates: [48.6895433, 9.6719037],
    telefon: '07161 616-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'pp-ludwigsburg',
    name: 'Polizeipräsidium Ludwigsburg',
    type: 'praesidium',
    city: 'Ludwigsburg',
    address: 'Friedrich-Ebert-Straße 30, 71638 Ludwigsburg',
    coordinates: [48.8933215, 9.199877],
    telefon: '07141 18-9',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-bietigheim-bissingen',
    name: 'Polizeirevier Bietigheim-Bissingen',
    type: 'revier',
    city: 'Bietigheim-Bissingen',
    address: 'Stuttgarter Straße 57, 74321 Bietigheim-Bissingen',
    coordinates: [48.9528362, 9.1371278],
    telefon: '07142 405-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-boblingen',
    name: 'Polizeirevier Böblingen',
    type: 'revier',
    city: 'Böblingen',
    address: 'Talstraße 50, 71034 Böblingen',
    coordinates: [48.68454, 9.00173],
    telefon: '07031 13-2500',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-ditzingen',
    name: 'Polizeirevier Ditzingen',
    type: 'revier',
    city: 'Ditzingen',
    address: 'An der Lache 1-5, 71254 Ditzingen',
    coordinates: [48.8271283, 9.0740374],
    telefon: '07156 4352-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-herrenberg',
    name: 'Polizeirevier Herrenberg',
    type: 'revier',
    city: 'Herrenberg',
    address: 'Alzentalstraße 1, 71083 Herrenberg',
    coordinates: [48.5940102, 8.8660863],
    telefon: '07032 2708-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-kornwestheim',
    name: 'Polizeirevier Kornwestheim',
    type: 'revier',
    city: 'Kornwestheim',
    address: 'Stuttgarter Straße 101, 70806 Kornwestheim',
    coordinates: [48.85746, 9.18566],
    telefon: '07154 1313-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-leonberg',
    name: 'Polizeirevier Leonberg',
    type: 'revier',
    city: 'Leonberg',
    address: 'Gerhart-Hauptmann-Straße 8, 71229 Leonberg',
    coordinates: [48.7983112, 9.0107918],
    telefon: '07152 605-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-ludwigsburg',
    name: 'Polizeirevier Ludwigsburg',
    type: 'revier',
    city: 'Ludwigsburg',
    address: 'Stuttgarter Straße 26-28, 71638 Ludwigsburg',
    coordinates: [48.8928428, 9.1942979],
    telefon: '07141 18-5353',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-marbach',
    name: 'Polizeirevier Marbach am Neckar',
    type: 'revier',
    city: 'Marbach am Neckar',
    address: 'Steinerstraße 2, 71672 Marbach am Neckar',
    coordinates: [48.9392523, 9.2573308],
    telefon: '07144 900-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-sindelfingen',
    name: 'Polizeirevier Sindelfingen',
    type: 'revier',
    city: 'Sindelfingen',
    address: 'Gartenstraße 4, 71063 Sindelfingen',
    coordinates: [48.7069732, 9.0039904],
    telefon: '07031 697-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  {
    id: 'rev-vaihingen-enz',
    name: 'Polizeirevier Vaihingen an der Enz',
    type: 'revier',
    city: 'Vaihingen an der Enz',
    address: 'Heilbronner Straße 17, 71665 Vaihingen an der Enz',
    coordinates: [48.9337714, 8.9583672],
    telefon: '07042 941-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ludwigsburg'
  },
  // ========================================
  // REUTLINGEN PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-reutlingen',
    name: 'Polizeipräsidium Reutlingen',
    type: 'praesidium',
    city: 'Reutlingen',
    address: 'Bismarckstraße 60, 72764 Reutlingen',
    coordinates: [48.492355, 9.220761],
    telefon: '07121 942-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-esslingen',
    name: 'Polizeirevier Esslingen',
    type: 'revier',
    city: 'Esslingen am Neckar',
    address: 'Agnespromenade 4, 73728 Esslingen am Neckar',
    coordinates: [48.743119, 9.304437],
    telefon: '0711 3990-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-filderstadt',
    name: 'Polizeirevier Filderstadt',
    type: 'revier',
    city: 'Filderstadt',
    address: 'Karl-Benz-Straße 23, 70794 Filderstadt',
    coordinates: [48.675288, 9.196178],
    telefon: '0711 7091-3',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-flughafen-stuttgart',
    name: 'Polizeirevier Flughafen Stuttgart',
    type: 'revier',
    city: 'Stuttgart',
    address: 'Flughafenstraße 36, 70629 Stuttgart',
    coordinates: [48.6911183, 9.1893812],
    telefon: '0711 78780-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-kirchheim-teck',
    name: 'Polizeirevier Kirchheim unter Teck',
    type: 'revier',
    city: 'Kirchheim unter Teck',
    address: 'Dettinger Straße 101, 73230 Kirchheim unter Teck',
    coordinates: [48.63936, 9.45455],
    telefon: '07021 501-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-metzingen',
    name: 'Polizeirevier Metzingen',
    type: 'revier',
    city: 'Metzingen',
    address: 'Ulmer Straße 96, 72555 Metzingen',
    coordinates: [48.53479, 9.29091],
    telefon: '07123/924 - 0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-muensingen',
    name: 'Polizeirevier Münsingen',
    type: 'revier',
    city: 'Münsingen',
    address: 'Karlstraße 2, 72525 Münsingen',
    coordinates: [48.4113143, 9.4916674],
    telefon: '07381/9364 - 0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-nuertingen',
    name: 'Polizeirevier Nürtingen',
    type: 'revier',
    city: 'Nürtingen',
    address: 'Europastraße 34, 72622 Nürtingen',
    coordinates: [48.62911, 9.33628],
    telefon: '07022 9224-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-pfullingen',
    name: 'Polizeirevier Pfullingen',
    type: 'revier',
    city: 'Pfullingen',
    address: 'Burgstraße 26, 72793 Pfullingen',
    coordinates: [48.4710361, 9.2297361],
    telefon: '07121/9918 - 0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-reutlingen',
    name: 'Polizeirevier Reutlingen',
    type: 'revier',
    city: 'Reutlingen',
    address: 'Burgstraße 27 - 29, 72764 Reutlingen',
    coordinates: [48.49069, 9.22134],
    telefon: '07121 942-3333',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-rottenburg',
    name: 'Polizeirevier Rottenburg',
    type: 'revier',
    city: 'Rottenburg am Neckar',
    address: 'Königstraße 9, 72108 Rottenburg am Neckar',
    coordinates: [48.4779814, 8.9347265],
    telefon: '07472 9801-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-tuebingen',
    name: 'Polizeirevier Tübingen',
    type: 'revier',
    city: 'Tübingen',
    address: 'Konrad-Adenauer-Straße 30, 72072 Tübingen',
    coordinates: [48.5096732, 9.0489565],
    telefon: '07071 972-1400',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-albstadt',
    name: 'Polizeirevier Albstadt',
    type: 'revier',
    city: 'Albstadt',
    address: 'Rudolf-Diesel-Straße 3, 72461 Albstadt',
    coordinates: [48.23104, 9.02733],
    telefon: '07432 955-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-balingen',
    name: 'Polizeirevier Balingen',
    type: 'revier',
    city: 'Balingen',
    address: 'Johann-Sebastian-Bach-Straße 2, 72336 Balingen',
    coordinates: [48.275667, 8.857329],
    telefon: '07433 264-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  {
    id: 'rev-hechingen',
    name: 'Polizeirevier Hechingen',
    type: 'revier',
    city: 'Hechingen',
    address: 'Heiligkreuzstraße 6, 72379 Hechingen',
    coordinates: [48.34886, 8.96347],
    telefon: '07471 9880-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-reutlingen'
  },
  // ========================================
  // ULM PRÄSIDIUM UND REVIERE
  // ========================================
  {
    id: 'pp-ulm',
    name: 'Polizeipräsidium Ulm',
    type: 'praesidium',
    city: 'Ulm',
    address: 'Münsterplatz 47, 89073 Ulm',
    coordinates: [48.397614, 9.9916439],
    telefon: '0731 188-0',
    notdienst24h: true,
    isActive: true,
    lastModified: new Date()
  },
  {
    id: 'rev-biberach',
    name: 'Polizeirevier Biberach',
    type: 'revier',
    city: 'Biberach an der Riß',
    address: 'Erlenweg 2, 88400 Biberach an der Riß',
    coordinates: [48.08738, 9.79488],
    telefon: '07351 447-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-ehingen',
    name: 'Polizeirevier Ehingen',
    type: 'revier',
    city: 'Ehingen (Donau)',
    address: 'Panoramastraße 6, 89584 Ehingen (Donau)',
    coordinates: [48.2780345, 9.7251251],
    telefon: '07391 588-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-eislingen',
    name: 'Polizeirevier Eislingen',
    type: 'revier',
    city: 'Eislingen/Fils',
    address: 'Ulmer Straße 34, 73054 Eislingen/Fils',
    coordinates: [48.6932276, 9.710758],
    telefon: '07161 851-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-geislingen',
    name: 'Polizeirevier Geislingen an der Steige',
    type: 'revier',
    city: 'Geislingen an der Steige',
    address: 'Eberhardstraße 12, 73312 Geislingen an der Steige',
    coordinates: [48.61701, 9.83882],
    telefon: '07331 9327-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-giengen',
    name: 'Polizeirevier Giengen an der Brenz',
    type: 'revier',
    city: 'Giengen an der Brenz',
    address: 'Schwagestraße 16, 89537 Giengen an der Brenz',
    coordinates: [48.6231803, 10.2387663],
    telefon: '07322 9653-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-goeppingen',
    name: 'Polizeirevier Göppingen',
    type: 'revier',
    city: 'Göppingen',
    address: 'Pfarrstraße 29, 73033 Göppingen',
    coordinates: [48.7050512, 9.6508052],
    telefon: '07161 63-2360',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-laupheim',
    name: 'Polizeirevier Laupheim',
    type: 'revier',
    city: 'Laupheim',
    address: 'Biberacher Straße 22, 88471 Laupheim',
    coordinates: [48.2252411, 9.8772729],
    telefon: '07392 9630-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-riedlingen',
    name: 'Polizeirevier Riedlingen',
    type: 'revier',
    city: 'Riedlingen',
    address: 'Zwiefalter Straße 16, 88499 Riedlingen',
    coordinates: [48.1557, 9.47819],
    telefon: '07371 938-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-uhingen',
    name: 'Polizeirevier Uhingen',
    type: 'revier',
    city: 'Uhingen',
    address: 'Im Brühl 5, 73066 Uhingen',
    coordinates: [48.70664, 9.57459],
    telefon: '07161 9381-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-ulm-mitte',
    name: 'Polizeirevier Ulm-Mitte',
    type: 'revier',
    city: 'Ulm',
    address: 'Münsterplatz 47, 89073 Ulm',
    coordinates: [48.397614, 9.9916439],
    telefon: '0731 188-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  },
  {
    id: 'rev-ulm-west',
    name: 'Polizeirevier Ulm-West',
    type: 'revier',
    city: 'Ulm',
    address: 'Römerstraße 122, 89077 Ulm',
    coordinates: [48.3860517, 9.9669864],
    telefon: '07 31 188-0',
    notdienst24h: false,
    isActive: true,
    lastModified: new Date(),
    parentId: 'pp-ulm'
  }
];
